name: Bug Report
description: Report a bug or unexpected behavior
labels: ["bug", "pending triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting! Please fill out the sections below.

  - type: textarea
    id: description
    attributes:
      label: Describe the bug
      description: What happened? What did you expect?
      placeholder: When I click on... I expected... but instead...
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      placeholder: |
        1. Go to...
        2. Click on...
        3. See error
    validations:
      required: true

  - type: input
    id: browser
    attributes:
      label: Browser
      placeholder: Chrome 120 / Firefox / Safari / Edge
    validations:
      required: true

  - type: input
    id: device
    attributes:
      label: Device
      placeholder: Desktop / Mobile (iPhone 14) / Tablet

  - type: textarea
    id: logs
    attributes:
      label: Console errors (if any)
      render: shell
