name: Feature Request
description: Suggest a new feature or improvement
labels: ["enhancement", "pending triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for your idea! Please describe what you'd like to see.

  - type: textarea
    id: problem
    attributes:
      label: What problem does this solve?
      placeholder: Currently, when I try to...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Describe your proposed solution
      placeholder: I would like to be able to...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      placeholder: I also thought about...

  - type: checkboxes
    id: contrib
    attributes:
      label: Contribution
      options:
        - label: I'm willing to help implement this
